version: '3.8'
services:
  samba:
    build: .
    container_name: samba
    hostname: samba
    environment:
      - DEFAULT_USER=${DEFAULT_USER:-customer}
      - SENHA_UBT=${SENHA_UBT:-troque!}
      - CONTAINER_FOLDER=${CONTAINER_FOLDER:-container-folder}
      - VSCODE_DATA_DIR=${VSCODE_DATA_DIR:-~/datadir}
    entrypoint: "/samba.sh"
    ports:
      - "445:445"
      - "139:139"
    restart: unless-stopped
